using System.Text;
using MagicExtract.Projections;
using Mutagen.Bethesda.Skyrim;

namespace MagicExtract;

public static class Reports
{
    private const string Header =
        "<!-- GENERATED by arch-docs/magic/tools/MagicExtract — do not hand-edit. Re-run Run-MagicExtract.ps1. -->\n";

    // ---- spells.csv — the flat balance sheet ------------------------------------------------

    public static void SpellsCsv(string path, Dataset<SpellDto> spells)
    {
        var sb = new StringBuilder();
        sb.AppendLine("formKey,editorId,name,school,type,castType,targetType,baseCost,computedAutoCost," +
                      "costDrift,manualCostCalc,chargeTime,effectCount,effect0Magnitude,effect0Area," +
                      "effect0Duration,winner,chainLength,winnerNeedsBees");
        // Grouped by school then type for spreadsheet work; schoolless spells sort last.
        // Name/FormKey tiebreakers keep the row order deterministic so re-runs diff cleanly.
        var ordered = spells.Winners
            .OrderBy(s => string.IsNullOrEmpty(s.School?.DisplayName) ? 1 : 0)
            .ThenBy(s => s.School?.DisplayName, StringComparer.Ordinal)
            .ThenBy(s => s.Type, StringComparer.Ordinal)
            .ThenBy(s => s.Name, StringComparer.Ordinal)
            .ThenBy(s => s.FormKey, StringComparer.Ordinal);
        foreach (var s in ordered)
        {
            var e0 = s.Effects?.FirstOrDefault();
            var p = s.Provenance!;
            sb.AppendLine(string.Join(",",
                Csv(s.FormKey), Csv(s.EditorId), Csv(s.Name), Csv(s.School?.DisplayName), Csv(s.Type),
                Csv(s.CastType), Csv(s.TargetType), s.Cost?.BaseCost.ToString() ?? "",
                s.Cost?.ComputedAutoCost?.ToString() ?? "", s.Cost?.CostDrift?.ToString() ?? "",
                s.Cost?.ManualCostCalc == true ? "true" : "false",
                s.ChargeTime.ToString(System.Globalization.CultureInfo.InvariantCulture),
                (s.Effects?.Count ?? 0).ToString(),
                e0?.Magnitude.ToString(System.Globalization.CultureInfo.InvariantCulture) ?? "",
                e0?.Area.ToString() ?? "", e0?.Duration.ToString() ?? "",
                Csv(p.Winner), p.Chain.Count.ToString(), p.WinnerNeedsBees ? "true" : "false"));
        }
        File.WriteAllText(path, sb.ToString(), new UTF8Encoding(false));
    }

    private static string Csv(string? v)
    {
        if (string.IsNullOrEmpty(v)) return "";
        return v.Contains(',') || v.Contains('"') || v.Contains('\n')
            ? "\"" + v.Replace("\"", "\"\"") + "\"" : v;
    }

    // ---- magic-overview.md --------------------------------------------------------------------

    public static void Overview(string path, ModlistLoadOrder lo,
        Dataset<SpellDto> spel, Dataset<MagicEffectDto> mgef, Dataset<EnchantmentDto> ench,
        Dataset<ScrollDto> scrl, Dataset<IngestibleDto> alch, Dataset<ShoutDto> shou,
        Dataset<LeveledSpellDto> lvsp, Dataset<GameSettingDto> gmst,
        IReadOnlyDictionary<ActorValue, string> schoolNames, bool costModelOk,
        int? beesLogCount, DateTime? beesLogTime)
    {
        var sb = new StringBuilder(Header);
        sb.AppendLine("# Zenderal magic — overview\n");
        sb.AppendLine("Load-order-winning values for every magic record in the installed Zenderal modlist. " +
                      "Data lives in [`data/`](data/); per-record conflicts in " +
                      "[`magic-conflicts.md`](magic-conflicts.md).\n");

        // BEES
        int needy = lo.Included.Count(e => e.NeedsBees);
        sb.AppendLine("## BEES dependency\n");
        sb.AppendLine($"**{needy} enabled plugins have HEDR 1.71** and load only because " +
                      "*Backported Extended ESL Support* is installed. Records whose winner is one of " +
                      "them carry `winnerNeedsBees: true`. Remove BEES and this dataset is wrong for " +
                      "all of them with no error anywhere.\n");
        if (beesLogCount is not null)
            sb.AppendLine($"Runtime corroboration: the BEES log reports **{beesLogCount}** plugins emulated " +
                          $"(log written {beesLogTime:yyyy-MM-dd HH:mm}).\n");

        // counts
        sb.AppendLine("## Datasets\n");
        sb.AppendLine("| Dataset | Winning records | With overrides | New (non-master) |");
        sb.AppendLine("|---|---:|---:|---:|");
        AppendCount(sb, spel); AppendCount(sb, mgef); AppendCount(sb, ench); AppendCount(sb, scrl);
        AppendCount(sb, alch); AppendCount(sb, shou); AppendCount(sb, lvsp); AppendCount(sb, gmst);
        sb.AppendLine();

        // top conflict winners
        sb.AppendLine("## Who wins the conflicts\n");
        sb.AppendLine("Plugins ranked by how many overridden magic records they end up winning:\n");
        var winners = new Dictionary<string, int>();
        foreach (var p in AllProvenance(spel, mgef, ench, scrl, alch, shou, lvsp))
            if (p.Chain.Count > 1)
                winners[p.Winner] = winners.GetValueOrDefault(p.Winner) + 1;
        sb.AppendLine("| Plugin | Conflicted records won |");
        sb.AppendLine("|---|---:|");
        foreach (var (name, count) in winners.OrderByDescending(kv => kv.Value).Take(20))
            sb.AppendLine($"| {name} | {count} |");
        sb.AppendLine();

        // schools
        sb.AppendLine("## Spells by school\n");
        sb.AppendLine("| School (Enderal name) | Actor value | Winning spells |");
        sb.AppendLine("|---|---|---:|");
        var bySchool = spel.Winners.GroupBy(s => s.School?.DisplayName ?? "(none)")
            .OrderByDescending(g => g.Count());
        foreach (var g in bySchool)
        {
            var av = g.First().School?.ActorValue ?? "—";
            sb.AppendLine($"| {g.Key} | {av} | {g.Count()} |");
        }
        sb.AppendLine();

        // cost model
        sb.AppendLine("## Cost model\n");
        sb.AppendLine("```");
        sb.AppendLine("effectCost    = floor( mgef.BaseCost * max(magnitude,1)^1.1 * durFactor^1.1 )");
        sb.AppendLine("durFactor     = 1 for Concentration effects (charged per second)");
        sb.AppendLine("                else (duration==0 ? 10 : duration) / 10");
        sb.AppendLine("spellAutoCost = Σ effectCost   // per-effect floor, then sum");
        sb.AppendLine("```");
        sb.AppendLine(costModelOk
            ? "\nFormula validated this run against base Enderal's own self-consistent spells (≥97% exact;" +
              " the remainder are four known authored-drift records in base Enderal itself)." +
              " `costDrift ≠ 0` on a non-`ManualCostCalc` spell means its stored cost no longer matches its" +
              " live effect data — an override edited a shared MGEF or the spell's durations without a CK" +
              " recompute. Those are rebalancing findings, filter for them in `spells.csv`.\n"
            : "\n**DISABLED this run** — formula validation fell below 97%, so `computedAutoCost`/`costDrift` are null.\n");
        sb.AppendLine("Runtime cost past `baseCost` is skill/perk-dependent; see `costModel` in " +
                      "[`data/lookups.json`](data/lookups.json) for the winning GMST curve " +
                      "(approximate — the 1/400 constant is engine-side).\n");

        // caveat
        sb.AppendLine("## What a record dump cannot see\n");
        sb.AppendLine("A lot of Enderal's magic balance lives in **Papyrus**, not records " +
                      "(e.g. `_00E_A1_ArcticWindME` carries `_00E_A1_ArcticWindSC` with a `PlayerLevel` " +
                      "property). Effects with attached scripts carry a `scripts[]` block in " +
                      "`magic-effects.json` — treat those as *flagged for manual reading* in " +
                      "`reference/base/EnderalScripts/source/scripts/`, not fully described here.\n");

        File.WriteAllText(path, sb.ToString(), new UTF8Encoding(false));
    }

    private static void AppendCount<TDto>(StringBuilder sb, Dataset<TDto> ds) where TDto : class, IRecordDto
    {
        int overridden = 0, newRecs = 0;
        foreach (var w in ds.Winners)
        {
            var p = w.Provenance!;
            if (p.Chain.Count > 1) overridden++;
            if (p.IsNewRecord) newRecs++;
        }
        sb.AppendLine($"| `{ds.Name}.json` ({ds.RecordType}) | {ds.Winners.Count} | {overridden} | {newRecs} |");
    }

    private static IEnumerable<ProvenanceDto> AllProvenance(params object[] datasets)
    {
        foreach (var ds in datasets)
        {
            var winners = (System.Collections.IEnumerable)ds.GetType().GetProperty("Winners")!.GetValue(ds)!;
            foreach (var w in winners)
                yield return ((IRecordDto)w).Provenance!;
        }
    }

    // ---- magic-conflicts.md ----------------------------------------------------------------------

    public static void Conflicts(string path, IConflictSource[] sources)
    {
        var sb = new StringBuilder(Header);
        sb.AppendLine("# Zenderal magic — conflict index\n");
        sb.AppendLine("Every magic record more than one plugin touches, with what the winner changed " +
                      "relative to the first carrier in the load order. `∅` = field absent/default on " +
                      "that side; `…` = complex value (see the JSON).\n");
        foreach (var src in sources)
        {
            var rows = src.ConflictRows().ToList();
            if (rows.Count == 0) continue;
            sb.AppendLine($"\n## {src.Name} ({rows.Count})\n");
            sb.AppendLine("| FormKey | EditorID | Name | Winner | Chain | Changes |");
            sb.AppendLine("|---|---|---|---|---|---|");
            foreach (var (fk, eid, name, prov, changes) in rows.OrderBy(r => r.FormKey, StringComparer.Ordinal))
            {
                string chain = string.Join(" → ", prov.Chain.Select(Shorten));
                string bees = prov.WinnerNeedsBees ? " ⚠BEES" : "";
                string ch = changes is null ? "—"
                    : Md(string.Join("; ", changes.Take(8))) + (changes.Count > 8 ? "; …" : "");
                sb.AppendLine($"| `{fk}` | `{eid ?? "—"}` | {Md(name ?? "—")} | {Shorten(prov.Winner)}{bees} | {chain} | {ch} |");
            }
        }
        File.WriteAllText(path, sb.ToString(), new UTF8Encoding(false));
    }

    private static string Shorten(string plugin) => plugin switch
    {
        "Skyrim.esm" => "Skyrim(=Enderal)",
        "Enderal - Forgotten Stories.esm" => "FS",
        "Enderal SE - Gameplay Overhaul.esp" => "EGO",
        _ => plugin.Replace(".esp", "").Replace(".esm", "").Replace(".esl", ""),
    };

    private static string Md(string s) => s.Replace("|", "\\|").Replace("\n", " ");
}
