#!/usr/bin/env python3
"""Regenerate the generated appendices in arch-docs/EGO/ from the serialized reference trees.

This is the tool that produced `conflict-index.md` and `new-records.md`. Everything it reads
is gitignored (`reference/`), so re-serialize first if the trees are missing:

    /spriggit-decompile-reference   ->  reference/base/{Skyrim,Update,EnderalFS}
    Spriggit serialize EGO's .esp   ->  reference/mods/EGO/esp

Usage (from the repo root):

    python arch-docs/EGO/tools/ego_report.py index     # build/refresh the FormKey cache
    python arch-docs/EGO/tools/ego_report.py appendices
    python arch-docs/EGO/tools/ego_report.py fields <RecordType>   # ad-hoc: what fields EGO changes
    python arch-docs/EGO/tools/ego_report.py diff <FormID>         # ad-hoc: base -> EGO diff

Requires PyYAML for `fields`/`diff`; `index` and `appendices` are regex-only.

NOTE on the index: EGO's own new records reuse the same 6-hex space as the records it
overrides, so new records live in a separate `EGOnew` map. Overrides are matched to a base
record by FormID *and* master, because FS and Skyrim.esm both contain most FormIDs.
"""
import difflib
import json
import os
import re
import sys
from collections import Counter, defaultdict

ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", ".."))
REF = os.path.join(ROOT, "reference")
DOCS = os.path.join(ROOT, "arch-docs", "EGO")
TREES = {
    "EGO": os.path.join(REF, "mods", "EGO", "esp"),
    "EnderalFS": os.path.join(REF, "base", "EnderalFS"),
    "Skyrim": os.path.join(REF, "base", "Skyrim"),
    "Update": os.path.join(REF, "base", "Update"),
}
CACHE = os.path.join(os.path.dirname(os.path.abspath(__file__)), ".ego_index.json")

FK = re.compile(r"^FormKey:\s*([0-9A-Fa-f]{6}):(.*?)\s*$", re.M)
EID = re.compile(r"^EditorID:\s*(.*?)\s*$", re.M)
NAME = re.compile(r"^Name:\n(?:[ \t]+\w+:.*\n)*?[ \t]+(?:Value|String):[ \t]*(.*?)[ \t]*$", re.M)
EGO_MASTER = "Enderal SE - Gameplay Overhaul.esp"


def build():
    idx = {"EGOnew": {}}
    for tree, path in TREES.items():
        if not os.path.isdir(path):
            sys.exit(f"missing reference tree: {path}")
        d = {}
        for dirpath, _, files in os.walk(path):
            for fn in files:
                if not fn.endswith(".yaml"):
                    continue
                fp = os.path.join(dirpath, fn)
                head = open(fp, encoding="utf-8", errors="replace").read(4000)
                m = FK.search(head)
                if not m:
                    continue
                e, n = EID.search(head), NAME.search(head)
                rel = os.path.relpath(fp, path)
                rec = [rel, e.group(1) if e else "", m.group(2), n.group(1) if n else ""]
                if tree == "EGO" and m.group(2) == EGO_MASTER:
                    idx["EGOnew"][m.group(1).upper()] = rec
                elif tree == "EGO":
                    # EGO overrides two masters, and four FormIDs collide across them
                    # (e.g. 01FE1F is a Book in FS.esm and a LeveledItem in Skyrim.esm),
                    # so the override map is keyed by the full FormKey.
                    d[m.group(1).upper() + ":" + m.group(2)] = rec
                else:
                    d[m.group(1).upper()] = rec
        idx[tree] = d
        print(f"  {tree}: {len(d)}", file=sys.stderr)
    print(f"  EGOnew: {len(idx['EGOnew'])}", file=sys.stderr)
    json.dump(idx, open(CACHE, "w"), separators=(",", ":"))
    return idx


def load():
    return json.load(open(CACHE)) if os.path.exists(CACHE) else build()


def rtype(rel):
    return rel.split(os.sep)[0]


def base_of(idx, fid, master):
    """The winning base record for FormKey fid:master (FS overrides Update/Skyrim)."""
    for t in ("EnderalFS", "Update", "Skyrim"):
        rec = idx[t].get(fid)
        if rec and rec[2] == master:
            return t, rec[0]
    return None, None


HEADER = """<!-- GENERATED by arch-docs/EGO/tools/ego_report.py - do not hand-edit. -->
"""


def appendices():
    idx = load()

    # ---- conflict index -------------------------------------------------
    by_type = defaultdict(list)
    injected = []
    for key, (rel, eid, master, _n) in idx["EGO"].items():
        fid = key.split(":")[0]
        t, _ = base_of(idx, fid, master)
        row = (eid or "(no EditorID)", fid, master)
        if t is None:
            injected.append((rtype(rel), *row))
        by_type[rtype(rel)].append(row)

    total = sum(len(v) for v in by_type.values())
    out = [HEADER, "# EGO conflict index — every record EGO overrides\n",
           f"`Enderal SE - Gameplay Overhaul.esp` overrides **{total}** existing records. "
           "Any Zenderal patch that touches a record listed here must forward EGO's version of "
           "every field it is not deliberately changing (CLAUDE.md guardrail 5).\n",
           "Suffix column is the master that *defines* the record: `Skyrim.esm` is base Enderal, "
           "`Enderal - Forgotten Stories.esm` is the FS expansion.\n"]
    if injected:
        out.append(f"\n## Injected records ({len(injected)})\n")
        out.append("FormIDs in a master's space that **the master does not define** — EGO creates "
                   "them. They read as overrides in xEdit but have no base record.\n")
        out.append("\n| Type | EditorID | FormKey |\n|---|---|---|")
        for t, eid, fid, master in sorted(injected):
            out.append(f"| {t} | `{eid}` | `{fid}:{master}` |")
        out.append("")
    for t in sorted(by_type):
        rows = sorted(by_type[t], key=lambda r: r[0].lower())
        out.append(f"\n## {t} ({len(rows)})\n")
        out.append("| EditorID | FormKey |\n|---|---|")
        for eid, fid, master in rows:
            out.append(f"| `{eid}` | `{fid}:{master}` |")
    write(os.path.join(DOCS, "conflict-index.md"), "\n".join(out) + "\n")

    # ---- new records ----------------------------------------------------
    rows = sorted((fid, rtype(rel), eid or "(no EditorID)", nm)
                  for fid, (rel, eid, _m, nm) in idx["EGOnew"].items())
    out = [HEADER, "# EGO new records — everything EGO adds\n",
           f"**{len(rows)}** records carrying the `:Enderal SE - Gameplay Overhaul.esp` suffix, "
           "in FormID order. These are safe to *reference* from a patch (declare EGO as a master); "
           "they are what disappears if EGO is removed from the list.\n",
           "\n| FormID | Type | EditorID | Name |\n|---|---|---|---|"]
    for fid, t, eid, nm in rows:
        out.append(f"| `{fid}` | {t} | `{eid}` | {nm} |")
    counts = Counter(t for _, t, _, _ in rows)
    out.append("\n## By record type\n\n| Type | New records |\n|---|---|")
    for t, c in counts.most_common():
        out.append(f"| {t} | {c} |")
    write(os.path.join(DOCS, "new-records.md"), "\n".join(out) + "\n")


def write(path, text):
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print(f"wrote {os.path.relpath(path, ROOT)} ({len(text)} bytes)", file=sys.stderr)


def fields(folder, verbose=False):
    import yaml
    idx = load()
    hist, n, miss = Counter(), 0, 0
    for key, (rel, eid, master, _n) in sorted(idx["EGO"].items()):
        fid = key.split(":")[0]
        if rtype(rel) != folder:
            continue
        bt, brel = base_of(idx, fid, master)
        if not brel:
            miss += 1
            continue
        n += 1
        a = yaml.safe_load(open(os.path.join(TREES[bt], brel), encoding="utf-8", errors="replace")) or {}
        b = yaml.safe_load(open(os.path.join(TREES["EGO"], rel), encoding="utf-8", errors="replace")) or {}
        diffs = sorted(k for k in set(a) | set(b) if k != "SpriggitSource" and a.get(k) != b.get(k))
        hist.update(diffs)
        if verbose:
            print(f"{fid} {eid[:50]:50s} {diffs}")
    print(f"-- {folder}: {n} overrides compared, {miss} injected --")
    for k, v in hist.most_common():
        print(f"  {v:5d}  {k}")


def diff(fid):
    idx = load()
    fid = fid.upper().zfill(6)
    ego = next((v for k, v in idx["EGO"].items() if k.split(":")[0] == fid), None)
    if not ego:
        rec = idx["EGOnew"].get(fid)
        print(open(os.path.join(TREES["EGO"], rec[0]), encoding="utf-8").read() if rec else "not in EGO")
        return
    bt, brel = base_of(idx, fid, ego[2])
    if not brel:
        print(f"(injected: {ego[2]} does not define {fid})")
        print(open(os.path.join(TREES["EGO"], ego[0]), encoding="utf-8").read())
        return
    a = open(os.path.join(TREES[bt], brel), encoding="utf-8", errors="replace").read().splitlines()
    b = open(os.path.join(TREES["EGO"], ego[0]), encoding="utf-8", errors="replace").read().splitlines()
    for line in difflib.unified_diff(a, b, bt, "EGO", lineterm="", n=2):
        print(line)


if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else "appendices"
    if cmd == "index":
        build()
    elif cmd == "appendices":
        appendices()
    elif cmd == "fields":
        fields(sys.argv[2], "-v" in sys.argv)
    elif cmd == "diff":
        diff(sys.argv[2])
    else:
        sys.exit(__doc__)
