FormKey: 09E104:Apocalypse - Magic of Skyrim.esp
EditorID: WB_RestorationNecro_Sound_FXS_Decompose
Type: Standard
Category: 07F80B:Skyrim.esm
SoundFiles:
- Data\Sound\FX\QST\QST_DA01_Azura_Magic_End_01_LPM.wav
OutputModel: 08F3E4:Skyrim.esm
LoopAndRumble:
  Loop: EnvelopeFast
PercentFrequencyShift: 40
PercentFrequencyVariance: 6
Priority: 128
StaticAttenuation: 29.52
