FormKey: 09EBCE:Apocalypse - Magic of Skyrim.esp
EditorID: WB_RestorationNecro_FXS_Decompose_Target
FillTexture: Effects\MagicCausticTile.dds
ParticleShaderTexture: Effects\MagicIceWisps.dds
HolesTexture: ''
MembranePaletteTexture: ApocNew\Grad_Restoration_Necro_DeathsDuet.dds
ParticlePaletteTexture: ''
MembraneSourceBlendMode: SourceAlpha
MembraneZTest: EqualTo
FillColorKey1: '#001E3148'
FillAlphaFadeInTime: 0.25
FillFullAlphaTime: 0.075
FillFadeOutTime: 0.25
FillPersistentAlphaRatio: 0.62
FillAlphaPulseFrequency: 1
FillTextureAnimationSpeedV: 0.1
EdgeEffectFallOff: 1.25
EdgeEffectColor: '#00485A25'
EdgeEffectAlphaFadeInTime: 0.25
EdgeEffectFullAlphaTime: 0.075
EdgeEffectAlphaFadeOutTime: 0.4
EdgeEffectPersistentAlphaRatio: 0.4
EdgeEffectAlphaPulseFrequency: 1
FillFullAlphaRatio: 0.62
EdgeEffectFullAlphaRatio: 0.5
MembraneDestBlendMode: SourceInvertedAlpha
ParticleSourceBlendMode: SourceAlpha
ParticleDestBlendMode: SourceInvertedAlpha
ParticleBirthRampUpTime: 0.1
ParticleFullBirthTime: 0.75
ParticleBirthRampDownTime: 0.25
ParticleFullBirthRatio: 20
ParticlePeristentCount: 20
ParticleLifetime: 0.95
ParticleLifetimePlusMinus: 0.1
ParticleInitialSpeedAlongNormal: 20
ParticleAccelerationAlongNormal: -10
ParticleInitialVelocity3: -55
ParticleAcceleration3: 60
ParticleScaleKey1: 18
ParticleScaleKey2: 50
ParticleScaleKey2Time: 1
ColorKey1: '#001E3348'
ColorKey2: '#001E3248'
ColorKey3: '#001E2648'
ColorKey2Alpha: 0.6
ColorKey2Time: 0.33
ColorKey3Time: 1
ParticleInitialSpeedAlongNormalPlusMinus: 5
ParticleInitialRotationDegreePlusMinus: 180
ParticleRotationSpeedDegreePerSecPlusMinus: 20
AddonModels: 09EBCC:Apocalypse - Magic of Skyrim.esp
HolesEndTime: 10
HolesStartValue: 255
EdgeColor: '#00FFFFFF'
TextureCountU: 2
TextureCountV: 2
AddonModelsFadeOutTime: 1.55
AddonModelsScaleStart: 0.25
AddonModelsScaleEnd: 1
AddonModelsScaleInTime: 0.15
AddonModelsScaleOutTime: 1.55
FillColorKey2: '#001E3548'
FillColorKey3: '#001E2D48'
FillColorKey1Scale: 1
FillColorKey2Scale: 1
FillColorKey3Scale: 1
FillColorKey2Time: 0.18
FillColorKey3Time: 1
ColorScale: 1
Flags:
- NoMembraneShader
- MembraneGrayscaleAlpha
- TextureEffectIgnoreAlpha
FillTextureScaleU: 3
FillTextureScaleV: 2
