FormKey: 095F3F:Apocalypse - Magic of Skyrim.esp
EditorID: WB_Res_Necro4_Effect_Decompose
Name:
  TargetLanguage: English
  Value: Decompose
MenuDisplayObject: 11D19E:Apocalypse - Magic of Skyrim.esp
Keywords:
- 01FCC4:Apocalypse - Magic of Skyrim.esp
- 035278:Apocalypse - Magic of Skyrim.esp
Flags:
- Hostile
- Detrimental
- NoArea
- FXPersist
- NoRecast
- PowerAffectsDuration
BaseCost: 3.45
MagicSkill: Restoration
CastingLight: 11D1AB:Apocalypse - Magic of Skyrim.esp
HitShader: 09EBCE:Apocalypse - Magic of Skyrim.esp
MinimumSkillLevel: 75
SpellmakingCastingTime: 0.5
Archetype:
  MutagenObjectType: MagicEffectCloakArchetype
  Association: 095F43:Apocalypse - Magic of Skyrim.esp
Projectile: 083FAD:Apocalypse - Magic of Skyrim.esp
CastType: FireAndForget
TargetType: Aimed
CastingArt: 11D19F:Apocalypse - Magic of Skyrim.esp
HitEffectArt: 083FAE:Apocalypse - Magic of Skyrim.esp
ImpactData: 11D1A4:Apocalypse - Magic of Skyrim.esp
SkillUsageMultiplier: 1
DualCastScale: 1.1
CastingSoundLevel: Normal
Sounds:
- Sound: 03E957:Skyrim.esm
- Type: Charge
  Sound: 03C8F9:Skyrim.esm
- Type: Ready
  Sound: 03F363:Skyrim.esm
- Type: Release
  Sound: 116E57:Apocalypse - Magic of Skyrim.esp
Description:
  TargetLanguage: English
  Value: Curses a nonmechanical target for <dur> seconds, allowing allies within <mag> feet of the target to absorb <15> points of Health per second from the target.
Conditions:
- MutagenObjectType: ConditionFloat
  Data:
    MutagenObjectType: IsActorConditionData
  ComparisonValue: 1
- MutagenObjectType: ConditionFloat
  Data:
    MutagenObjectType: HasKeywordConditionData
    Keyword: 01397A:Skyrim.esm
- MutagenObjectType: ConditionFloat
  Data:
    MutagenObjectType: GetDeadConditionData
